### ISSUE TITLE
Redux persist v5

### ISSUE THREAD

**Issue by byoxtheimer** [abersager/redux-persist-cookie-storage#10]
Hi is this package compatible with redux persist v5.4 since it no longer has the autorehydrate function? And if it is what do I replace the call to auto rehydrate with?

**Comment by rt2zz** [comment]
yes this should work just fine with v5, just follow the docs on redux-persist and add cookie storage to your persist config.

**Comment by cyrilchapon** [comment]
Doc must be updated, doesn't it ?

**Comment by aforty** [comment]
Additional confusion stems from the fact that the version shipped on npm is not what's currently in master but instead what's in the `server-support` branch.

Better (but not great) docs here:
https://github.com/abersager/redux-persist-cookie-storage/tree/server-support

**Comment by abersager** [comment]
Apologies for the long delay. Just published 1.0.0, which is redux-persist 5 compatible.
