### ISSUE TITLE
TypeError: this.cookies.get is not a function

### ISSUE THREAD

**Issue by sinapirani** [abersager/redux-persist-cookie-storage#23]
hello. i created a redux store with reduxjs/toolkit and redux-presist and youre package but it dont work.
please help to solve that.

> `import { combineReducers, configureStore } from "@reduxjs/toolkit";
> import cartSlice from './cartSlice'
> import {CookieStorage} from "redux-persist-cookie-storage";
> import {persistReducer, persistStore} from 'redux-persist'
> import thunk from "redux-thunk";
> import userSlice from "./userSlice";
> import Cookies from 'cookie-js'
> 
> const presistConfig = {
>     key: 'root',
>     storage: new CookieStorage(Cookies),
>     stateReconciler(inboundState, originalState) {
>       // Ignore state from cookies, only use preloadedState from window object
>       return originalState
>     }
> } 
> 
> const reducer = combineReducers({cartSlice,userSlice})
> const local = persistReducer(presistConfig, reducer)
> 
> const store = configureStore({
>   reducer: {
>     local
>   },
>   devTools: true,
>   middleware: [thunk],
> });
> 
> export const persistor = persistStore(store);
> export default store`
>

**Comment by ashkankiani** [comment]
I have this problem too. solution??

**Comment by ashkankiani** [comment]
solved by me.
change
`import Cookies from 'cookies-js'`
to
`import Cookies from 'js-cookie'`
and import package
